# Generated by Django 3.2 on 2022-05-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fletes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado_solicitud',
            field=models.CharField(choices=[('Guardada', 'Guardada'), ('Publicada', 'Publicada'), ('Cotizada', 'Cotizada'), ('Asignada', 'Asignada'), ('Pagada', 'Pagada'), ('Cancelada', 'Cancelada')], default='Guardada', max_length=40, verbose_name='Estado de la solicitud'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='estado_viaje',
            field=models.CharField(choices=[('Creado', 'Creado'), ('Iniciado', 'Iniciado'), ('Cerrado', 'Cerrado'), ('Pendiente pago', 'Pendiente pago'), ('Terminado', 'Terminado'), ('Disputa', 'Disputa'), ('Accidente', 'Accidente')], default='Creado', max_length=40, verbose_name='Estado'),
        ),
    ]
