# Generated by Django 3.2 on 2021-11-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fletes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='volumen_carga',
            field=models.FloatField(verbose_name='Volumen de la carga(mts3)'),
        ),
    ]
