# Generated by Django 3.2 on 2022-03-23 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fletes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='nivel_seguro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fletes.seguro', verbose_name='Nivel de Seguro'),
        ),
    ]
