# Generated by Django 3.2 on 2022-01-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fletes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicilios',
            name='latitud',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='domicilios',
            name='longitud',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud'),
        ),
    ]
