# Generated by Django 3.2 on 2021-11-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fletes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='estado_cotizacion',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada'), ('Confirmada', 'Confirmada')], default='Pendiente', max_length=40, verbose_name='Estado'),
        ),
    ]
