# Generated by Django 3.2 on 2022-01-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fletes', '0003_auto_20220105_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='km_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Km totales del viaje'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='tiempo_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Tiempo total del viaje'),
        ),
    ]
