# Generated by Django 3.2 on 2022-01-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fletes', '0003_alter_cotizacion_nivel_seguro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='checkoutUrl',
            field=models.URLField(default=''),
        ),
    ]
