# Generated by Django 3.2 on 2021-11-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fletes', '0003_alter_cotizacion_estado_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
