# Generated by Django 3.2 on 2022-05-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fletes', '0003_auto_20220509_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado_solicitud',
            field=models.CharField(choices=[('Guardada', 'Guardada'), ('Publicada', 'Publicada'), ('Cotizada', 'Cotizada'), ('Asignada', 'Asignada'), ('Pagada', 'Pagada'), ('Cancelada', 'Cancelada'), ('Vencida', 'Vencida')], default='Guardada', max_length=40, verbose_name='Estado de la solicitud'),
        ),
    ]
