# Generated by Django 3.2 on 2022-03-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fletes', '0003_alter_cotizacion_nivel_seguro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='total',
            field=models.FloatField(blank=True, null=True, verbose_name='Total'),
        ),
    ]
