# Generated by Django 3.2 on 2022-05-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fletes', '0004_alter_solicitud_estado_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='estado_viaje',
            field=models.CharField(choices=[('Creado', 'Creado'), ('Iniciado', 'Iniciado'), ('Cerrado', 'Cerrado'), ('Pendiente de pago', 'Pendiente de pago'), ('Terminado', 'Terminado'), ('Disputa', 'Disputa'), ('Accidente', 'Accidente')], default='Creado', max_length=40, verbose_name='Estado'),
        ),
    ]
