# Generated by Django 3.2 on 2022-01-11 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fletes', '0004_auto_20220106_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicilios',
            name='google_format',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Formato de dirección Google'),
        ),
        migrations.AddField(
            model_name='domicilios',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='Es válido'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='domicilio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fletes.domicilios', verbose_name='Origen'),
        ),
    ]
