# Generated by Django 3.2 on 2022-02-10 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fletes', '0004_cotizacion_checkouturl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('cotizacion_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='fletes.cotizacion')),
                ('estado_solicitud', models.CharField(choices=[('Creado', 'Creado'), ('Iniciado', 'Iniciado'), ('Cerrado', 'Cerrado'), ('Terminado', 'Terminado'), ('Disputa', 'Disputa'), ('Accidente', 'Accidente')], default='Creado', max_length=40, verbose_name='Estado')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_llegada', models.TimeField(verbose_name='Hora de llegada')),
                ('localizacion_transportista', models.CharField(max_length=40, verbose_name='Localización de transportista')),
                ('nip', models.IntegerField(verbose_name='NIP de seguridad de viaje')),
                ('comentarios', models.TextField()),
                ('es_validado', models.BooleanField(default=False, verbose_name='¿Esta válido por cliente?')),
            ],
        ),
        migrations.AddField(
            model_name='destino',
            name='foto1',
            field=models.ImageField(blank=True, null=True, upload_to='unidades_pics', verbose_name='Foto 1 evidencia de entrega'),
        ),
        migrations.AddField(
            model_name='destino',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to='unidades_pics', verbose_name='Foto 2 evidencia de entrega'),
        ),
        migrations.AddField(
            model_name='destino',
            name='foto3',
            field=models.ImageField(blank=True, null=True, upload_to='unidades_pics', verbose_name='Foto 3 evidencia de entrega'),
        ),
        migrations.AddField(
            model_name='destino',
            name='foto4',
            field=models.ImageField(blank=True, null=True, upload_to='unidades_pics', verbose_name='Foto 4 evidencia de entrega'),
        ),
        migrations.AddField(
            model_name='destino',
            name='foto5',
            field=models.ImageField(blank=True, null=True, upload_to='unidades_pics', verbose_name='Foto 5 evidencia de entrega'),
        ),
    ]
