# Generated by Django 3.2 on 2021-12-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fletes', '0005_alter_solicitud_estado_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='estado_cotizacion',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=40, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado_solicitud',
            field=models.CharField(choices=[('Guardada', 'Guardada'), ('Publicada', 'Publicada'), ('Cotizada', 'Cotizada'), ('Asignada', 'Asignada'), ('Cancelada', 'Cancelada')], default='Guardada', max_length=40, verbose_name='Estado'),
        ),
    ]
