# Generated by Django 3.2 on 2022-01-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fletes', '0005_auto_20220111_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicilios',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Google place ID'),
        ),
        migrations.AlterField(
            model_name='domicilios',
            name='google_format',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección completa'),
        ),
    ]
