# Generated by Django 3.2 on 2022-02-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fletes', '0005_auto_20220209_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de inicio'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='hora_llegada',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de llegada'),
        ),
    ]
