# Generated by Django 3.2 on 2022-03-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fletes', '0005_auto_20220324_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilios',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Google place ID'),
        ),
    ]
