# Generated by Django 3.2 on 2021-12-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fletes', '0006_auto_20211203_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='material_peligroso',
            field=models.BooleanField(default=False, verbose_name='Es material peligroso'),
        ),
    ]
