# Generated by Django 3.2 on 2022-02-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fletes', '0006_auto_20220209_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='nip',
            field=models.IntegerField(blank=True, null=True, verbose_name='NIP de seguridad de viaje'),
        ),
    ]
