# Generated by Django 3.2 on 2022-03-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fletes', '0006_alter_domicilios_google_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='aceptar_tyc',
            field=models.BooleanField(default=False, verbose_name='Aceptación de términos y condiciones de seguro'),
        ),
    ]
