# Generated by Django 3.2 on 2022-02-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fletes', '0007_auto_20220209_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='folio',
            field=models.CharField(default='', editable=False, max_length=20, verbose_name='Folio'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='slug',
            field=models.SlugField(default='', null=True),
        ),
    ]
