# Generated by Django 3.2 on 2021-12-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fletes', '0007_solicitud_material_peligroso'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='motivo_cancelación',
            field=models.TextField(default='', verbose_name='Motivo de cancelación'),
        ),
    ]
