# Generated by Django 3.2 on 2021-12-08 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fletes', '0008_solicitud_motivo_cancelación'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='motivo_cancelación',
            new_name='motivo_cancelacion',
        ),
    ]
