# Generated by Django 3.2 on 2021-12-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fletes', '0009_rename_motivo_cancelación_solicitud_motivo_cancelacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='motivo_cancelacion',
            field=models.TextField(default='', verbose_name='Motivo de cancelación'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado_cotizacion',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada'), ('Solicitud cancelada', 'Solicitud cancelada')], default='Pendiente', max_length=40, verbose_name='Estado'),
        ),
    ]
