# Generated by Django 3.2 on 2021-12-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fletes', '0010_auto_20211207_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, default='', verbose_name='Motivo de cancelación'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, default='', verbose_name='Motivo de cancelación'),
        ),
    ]
