# Generated by Django 3.2 on 2022-04-18 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fletes', '0010_auto_20220413_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='cotizacion_id',
        ),
        migrations.AddField(
            model_name='viaje',
            name='orden_id',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='fletes.orden'),
            preserve_default=False,
        ),
    ]
