# Generated by Django 3.2 on 2022-04-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fletes', '0011_auto_20220418_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='orden_status',
            field=models.CharField(blank=True, choices=[('Pagada', 'Pagada'), ('Pendiente', 'Pendiente')], max_length=200, null=True),
        ),
    ]
