# Generated by Django 3.2 on 2021-12-09 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fletes', '0011_auto_20211208_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='estado_cotizacion',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada'), ('Solicitud cancelada por cliente', 'Solicitud cancelada por cliente')], default='Pendiente', max_length=40, verbose_name='Estado'),
        ),
    ]
