# Generated by Django 3.2 on 2022-04-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fletes', '0014_auto_20220419_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de cancelación'),
        ),
    ]
