# Generated by Django 3.2 on 2022-04-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fletes', '0015_alter_solicitud_motivo_cancelacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='link_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='link_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
