# Generated by Django 3.2 on 2022-04-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fletes', '0016_auto_20220425_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='folio',
            field=models.CharField(max_length=20, unique=True, verbose_name='Folio'),
        ),
    ]
