# Generated by Django 3.2 on 2022-04-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fletes', '0017_alter_cotizacion_folio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='orden_status',
            field=models.CharField(blank=True, choices=[('paid', 'paid'), ('Pendiente', 'Pendiente')], max_length=200, null=True),
        ),
    ]
