# Generated by Django 3.2 on 2022-04-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fletes', '0018_alter_orden_orden_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='orden_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
