# Generated by Django 3.2 on 2021-11-04 23:24

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254)),
                ('es_transportista', models.BooleanField(default=False)),
                ('es_cliente', models.BooleanField(default=False)),
                ('es_empresa', models.BooleanField(default=False, help_text='Las empresas son personas morales', verbose_name='Persona moral')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Encierro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre para identificar el encierro')),
                ('calle', models.CharField(max_length=100, verbose_name='Calle')),
                ('num_ext', models.CharField(max_length=100, verbose_name='Numero exterior')),
                ('num_int', models.CharField(blank=True, default='', max_length=100, verbose_name='Numero interior')),
                ('colonia', models.CharField(max_length=100, verbose_name='Colonia')),
                ('municipio', models.CharField(max_length=100, null=True, verbose_name='Municipio o alcadía')),
                ('cp', models.CharField(max_length=100, verbose_name='Código postal')),
                ('estado', models.CharField(choices=[('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California'), ('Baja California Sur', 'Baja California Sur'), ('Campeche', 'Campeche'), ('Coahuila de Zaragoza', 'Coahuila de Zaragoza'), ('Colima', 'Colima'), ('Chiapas', 'Chiapas'), ('Chihuahua', 'Chihuahua'), ('CDMX', 'CDMX'), ('Durango', 'Durango'), ('Guanajuato', 'Guanajuato'), ('Guerrero', 'Guerrero'), ('Hidalgo', 'Hidalgo'), ('Jalisco', 'Jalisco'), ('México', 'México'), ('Michoacán de Ocampo', 'Michoacán de Ocampo'), ('Morelos', 'Morelos'), ('Nayarit', 'Nayarit'), ('Nuevo León', 'Nuevo León'), ('Oaxaca', 'Oaxaca'), ('Puebla', 'Puebla'), ('Querétaro', 'Querétaro'), ('Quintana Roo', 'Quintana Roo'), ('San Luis Potosí', 'San Luis Potosí'), ('Sinaloa', 'Sinaloa'), ('Sonora', 'Sonora'), ('Tabasco', 'Tabasco'), ('Tamaulipas', 'Tamaulipas'), ('Tlaxcala', 'Tlaxcala'), ('Veracruz de Ignacio de la Llave', 'Veracruz de Ignacio de la Llave'), ('Yucatán', 'Yucatán'), ('Zacatecas', 'Zacatecas')], max_length=40, verbose_name='Estado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuarios.myuser')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics', verbose_name='Foto de perfil')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre o Razon social(empresas)')),
                ('ape_pat', models.CharField(blank=True, default=' ', max_length=100, verbose_name='Apellido paterno')),
                ('ape_mat', models.CharField(blank=True, default=' ', max_length=100, verbose_name='Apellido materno')),
                ('telefono', models.CharField(max_length=100, verbose_name='Numero teléfonico a 10 digitos')),
                ('calle', models.CharField(max_length=100, verbose_name='Calle')),
                ('num_ext', models.CharField(max_length=100, verbose_name='Numero exterior')),
                ('num_int', models.CharField(blank=True, default='', max_length=100, verbose_name='Numero interior')),
                ('colonia', models.CharField(max_length=100, verbose_name='Colonia')),
                ('municipio', models.CharField(max_length=100, verbose_name='Municipio o alcadía')),
                ('cp', models.CharField(max_length=100, verbose_name='Código postal')),
                ('estado', models.CharField(choices=[('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California'), ('Baja California Sur', 'Baja California Sur'), ('Campeche', 'Campeche'), ('Coahuila de Zaragoza', 'Coahuila de Zaragoza'), ('Colima', 'Colima'), ('Chiapas', 'Chiapas'), ('Chihuahua', 'Chihuahua'), ('CDMX', 'CDMX'), ('Durango', 'Durango'), ('Guanajuato', 'Guanajuato'), ('Guerrero', 'Guerrero'), ('Hidalgo', 'Hidalgo'), ('Jalisco', 'Jalisco'), ('México', 'México'), ('Michoacán de Ocampo', 'Michoacán de Ocampo'), ('Morelos', 'Morelos'), ('Nayarit', 'Nayarit'), ('Nuevo León', 'Nuevo León'), ('Oaxaca', 'Oaxaca'), ('Puebla', 'Puebla'), ('Querétaro', 'Querétaro'), ('Quintana Roo', 'Quintana Roo'), ('San Luis Potosí', 'San Luis Potosí'), ('Sinaloa', 'Sinaloa'), ('Sonora', 'Sonora'), ('Tabasco', 'Tabasco'), ('Tamaulipas', 'Tamaulipas'), ('Tlaxcala', 'Tlaxcala'), ('Veracruz de Ignacio de la Llave', 'Veracruz de Ignacio de la Llave'), ('Yucatán', 'Yucatán'), ('Zacatecas', 'Zacatecas')], max_length=40, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='DatosFiscales',
            fields=[
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre o Razon social(empresas)')),
                ('ape_pat', models.CharField(blank=True, default=' ', max_length=100, verbose_name='Apellido paterno')),
                ('ape_mat', models.CharField(blank=True, default=' ', max_length=100, verbose_name='Apellido materno')),
                ('calle', models.CharField(max_length=100, verbose_name='Calle')),
                ('num_ext', models.CharField(max_length=100, verbose_name='Numero exterior')),
                ('num_int', models.CharField(blank=True, default='', max_length=100, verbose_name='Numero interior')),
                ('colonia', models.CharField(max_length=100, verbose_name='Colonia')),
                ('municipio', models.CharField(max_length=100, null=True, verbose_name='Municipio o alcadía')),
                ('cp', models.CharField(max_length=100, verbose_name='Código postal')),
                ('estado', models.CharField(choices=[('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California'), ('Baja California Sur', 'Baja California Sur'), ('Campeche', 'Campeche'), ('Coahuila de Zaragoza', 'Coahuila de Zaragoza'), ('Colima', 'Colima'), ('Chiapas', 'Chiapas'), ('Chihuahua', 'Chihuahua'), ('CDMX', 'CDMX'), ('Durango', 'Durango'), ('Guanajuato', 'Guanajuato'), ('Guerrero', 'Guerrero'), ('Hidalgo', 'Hidalgo'), ('Jalisco', 'Jalisco'), ('México', 'México'), ('Michoacán de Ocampo', 'Michoacán de Ocampo'), ('Morelos', 'Morelos'), ('Nayarit', 'Nayarit'), ('Nuevo León', 'Nuevo León'), ('Oaxaca', 'Oaxaca'), ('Puebla', 'Puebla'), ('Querétaro', 'Querétaro'), ('Quintana Roo', 'Quintana Roo'), ('San Luis Potosí', 'San Luis Potosí'), ('Sinaloa', 'Sinaloa'), ('Sonora', 'Sonora'), ('Tabasco', 'Tabasco'), ('Tamaulipas', 'Tamaulipas'), ('Tlaxcala', 'Tlaxcala'), ('Veracruz de Ignacio de la Llave', 'Veracruz de Ignacio de la Llave'), ('Yucatán', 'Yucatán'), ('Zacatecas', 'Zacatecas')], max_length=40, verbose_name='Estado')),
                ('telefono', models.CharField(max_length=30, verbose_name='Numero teléfonico')),
                ('rfc', models.CharField(max_length=30)),
                ('es_empresa', models.BooleanField(default=False, help_text='Las empresas son personas morales', verbose_name='Persona moral')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuarios.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuarios.myuser')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics', verbose_name='Foto de perfil')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre o Razon social(empresas)')),
                ('ape_pat', models.CharField(blank=True, default=' ', max_length=100, verbose_name='Apellido paterno')),
                ('ape_mat', models.CharField(blank=True, default=' ', max_length=100, verbose_name='Apellido materno')),
                ('telefono', models.CharField(max_length=100, verbose_name='Numero teléfonico a 10 digitos')),
                ('calle', models.CharField(max_length=100, verbose_name='Calle')),
                ('num_ext', models.CharField(max_length=100, verbose_name='Numero exterior')),
                ('num_int', models.CharField(blank=True, default='', max_length=100, verbose_name='Numero interior')),
                ('colonia', models.CharField(max_length=100, verbose_name='Colonia')),
                ('municipio', models.CharField(max_length=100, verbose_name='Municipio o alcadía')),
                ('cp', models.CharField(max_length=100, verbose_name='Código postal')),
                ('estado', models.CharField(choices=[('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California'), ('Baja California Sur', 'Baja California Sur'), ('Campeche', 'Campeche'), ('Coahuila de Zaragoza', 'Coahuila de Zaragoza'), ('Colima', 'Colima'), ('Chiapas', 'Chiapas'), ('Chihuahua', 'Chihuahua'), ('CDMX', 'CDMX'), ('Durango', 'Durango'), ('Guanajuato', 'Guanajuato'), ('Guerrero', 'Guerrero'), ('Hidalgo', 'Hidalgo'), ('Jalisco', 'Jalisco'), ('México', 'México'), ('Michoacán de Ocampo', 'Michoacán de Ocampo'), ('Morelos', 'Morelos'), ('Nayarit', 'Nayarit'), ('Nuevo León', 'Nuevo León'), ('Oaxaca', 'Oaxaca'), ('Puebla', 'Puebla'), ('Querétaro', 'Querétaro'), ('Quintana Roo', 'Quintana Roo'), ('San Luis Potosí', 'San Luis Potosí'), ('Sinaloa', 'Sinaloa'), ('Sonora', 'Sonora'), ('Tabasco', 'Tabasco'), ('Tamaulipas', 'Tamaulipas'), ('Tlaxcala', 'Tlaxcala'), ('Veracruz de Ignacio de la Llave', 'Veracruz de Ignacio de la Llave'), ('Yucatán', 'Yucatán'), ('Zacatecas', 'Zacatecas')], max_length=40, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('año', models.IntegerField(choices=[(1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=2021, verbose_name='Año')),
                ('tipo_caja', models.CharField(max_length=50, verbose_name='Tipo de caja')),
                ('capacidad_carga', models.FloatField(verbose_name='Capacidad de carga(toneladas)')),
                ('tarjeta_circulacion', models.CharField(default='', max_length=50, verbose_name='Tarjeta de circulación')),
                ('tarjeta_circulacion_foto', models.ImageField(upload_to='tarjetas_circulacion', verbose_name='Foto de tarjeta de circulación')),
                ('foto1', models.ImageField(upload_to='unidades_pics', verbose_name='Foto 1 de unidad')),
                ('foto2', models.ImageField(upload_to='unidades_pics', verbose_name='Foto 1 de unidad')),
                ('encierro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.encierro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('ape_pat', models.CharField(default=' ', max_length=100, verbose_name='Apellido paterno')),
                ('ape_mat', models.CharField(default=' ', max_length=100, verbose_name='Apellido materno')),
                ('telefono', models.CharField(max_length=50, verbose_name='Numero teléfonico')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
