# Generated by Django 3.2 on 2021-11-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportista',
            name='califiacion',
            field=models.IntegerField(default=5, verbose_name='Calificación'),
        ),
    ]
