# Generated by Django 3.2 on 2022-07-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidades',
            name='tarjeta_circulacion_verificador_foto',
            field=models.ImageField(blank=True, null=True, upload_to='verificaciones', verbose_name='Foto de tarjeta de circulación del verificador'),
        ),
        migrations.AlterField(
            model_name='unidades',
            name='verificador_foto_unidad',
            field=models.ImageField(blank=True, null=True, upload_to='verificaciones', verbose_name='Foto de unidad del verificador'),
        ),
    ]
