# Generated by Django 3.2 on 2022-03-16 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportista',
            name='telefonia_movil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.telefonias', verbose_name='Telefonía Movil'),
        ),
    ]
