# Generated by Django 3.2 on 2021-12-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidades',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to='unidades_pics', verbose_name='Foto 2 de unidad'),
        ),
    ]
