# Generated by Django 3.2 on 2022-06-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportista',
            name='fecha_vencimiento_licencia',
            field=models.DateTimeField(blank=True, verbose_name='Fecha de vencimiento de la licencia de manejo'),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='licencia_conducir_foto',
            field=models.ImageField(blank=True, upload_to='licencias_transportistas', verbose_name='Foto de licencia de conducir'),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='licencia_conducir_mp_foto',
            field=models.ImageField(blank=True, upload_to='licencias_transportistas', verbose_name='Foto de licencia de conducir material peligroso'),
        ),
    ]
