# Generated by Django 3.2 on 2021-10-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ape_mat',
            field=models.CharField(blank=True, default=' ', max_length=100, verbose_name='Apellido materno'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ape_pat',
            field=models.CharField(blank=True, default=' ', max_length=100, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='datosfiscales',
            name='ape_mat',
            field=models.CharField(blank=True, default=' ', max_length=100, verbose_name='Apellido materno'),
        ),
        migrations.AlterField(
            model_name='datosfiscales',
            name='ape_pat',
            field=models.CharField(blank=True, default=' ', max_length=100, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='ape_mat',
            field=models.CharField(blank=True, default=' ', max_length=100, verbose_name='Apellido materno'),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='ape_pat',
            field=models.CharField(blank=True, default=' ', max_length=100, verbose_name='Apellido paterno'),
        ),
    ]
