# Generated by Django 3.2 on 2021-12-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_transportista_califiacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidades',
            name='placa',
            field=models.CharField(default='', max_length=50, verbose_name='Placa'),
        ),
    ]
