# Generated by Django 3.2 on 2022-05-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_transportista_telefonia_movil'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportista',
            name='licencia_mp',
            field=models.BooleanField(default=False, verbose_name='Permiso de transportación de matarial peligroso'),
        ),
    ]
