# Generated by Django 3.2 on 2022-07-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_datosfiscales_verificador_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='encierro',
            name='verificador_direccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección del domicilio fiscal'),
        ),
    ]
