# Generated by Django 3.2 on 2021-12-01 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_unidades_placa'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportista',
            name='viajes_realizados',
            field=models.IntegerField(default=0, verbose_name='Calificación'),
        ),
    ]
