# Generated by Django 3.2 on 2021-11-01 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_myuser_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_email_verified',
        ),
    ]
