# Generated by Django 3.2 on 2021-12-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_transportista_viajes_realizados'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportista',
            old_name='califiacion',
            new_name='calificacion',
        ),
        migrations.AlterField(
            model_name='transportista',
            name='viajes_realizados',
            field=models.IntegerField(default=0, verbose_name='Viajes realizados'),
        ),
    ]
