# Generated by Django 3.2 on 2021-12-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20211130_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='penalizaciones',
            field=models.IntegerField(default=0, verbose_name='Número de penalizacionos'),
        ),
    ]
