# Generated by Django 3.2 on 2021-11-04 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_encierro_unidades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encierro',
            name='locacion',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='unidades',
            name='capacidad_carga',
            field=models.FloatField(verbose_name='Capacidad de carga(toneladas)'),
        ),
        migrations.AlterField(
            model_name='unidades',
            name='foto1',
            field=models.ImageField(upload_to='unidades_pics', verbose_name='Foto 1 de unidad'),
        ),
        migrations.AlterField(
            model_name='unidades',
            name='foto2',
            field=models.ImageField(upload_to='unidades_pics', verbose_name='Foto 1 de unidad'),
        ),
    ]
