from django.urls import include, path

from .views import *

app_name = 'fletes'
urlpatterns = [
    path('solicitudes/', SolicitudListView.as_view(), name='solicitudes'),
    path('solicitudes/cliente', SolicitudClienteListView.as_view(), name='solicitudes-cliente'),
    path('solicitud/agregar/', SolicitudesAgregar.as_view(), name='agregar-solicitud'),
    path('solicitud/detalle/<slug:slug>', SolicitudDetalle.as_view(), name='detalle-solicitud'),
    path('solicitud/editar/<slug:slug>', SolicitudUpdate.as_view(), name='editar-solicitud'),
    path('solicitud/editar/<slug:slug>/hora', SolicitudUpdateHora.as_view(), name='editar-solicitud-hora'),
    path('solicitud/cancelar/<slug:slug>', SolicitudCancel.as_view(), name='cancelar-solicitud'),
    path('solicitud/eliminar/<int:id>', SolicitudDelete, name='delete-solicitud'),
    path('solicitud/finalizar/<int:id>', FinalizarSolicitud, name='finalizar-solicitud'),
    path('solicitud/agregar/destino/<int:id>', DestinoAgregar.as_view(), name='agregar-destino'),
    path('solicitud/editar/destino/<int:pk>', DestinoUpdate.as_view(), name='editar-destino'),
    path('solicitud/eliminar/destino/<int:id>', DestinoDelete, name='delete-destino'),
    path('domicilios/', DomiciliosListView.as_view(), name='domicilios'),
    path('domicilio/agregar/', DomicilioAgregar.as_view(), name='agregar-domiclio'),
    path('domicilio/editar/<slug:slug>', DomiciliosUpdate.as_view(), name='update-domicilio'),
    path('domicilio/eliminar/<slug:slug>', DomiciliosDelete, name='delete-domicilio'),
    path('cotizaciones/', CotizacionListView.as_view(), name='cotizaciones'),
    path('cotizacion/agregar/<slug:slug>', CotizacionAgregar.as_view(), name='agregar-cotizacion'),
    path('cotizaciones/eliminar/<slug:slug>', ContizacionDelete, name='delete-cotizacion'),
    path('cotizaciones/<slug:slug>', CotizacionListClienteView.as_view(), name='cotizaciones-cliente'),
    path('cotizacion/aceptar/<slug:slug>', aceptarCotizacion, name='aceptar-cotizacion'),
    path('cotizacion/confirmar/<slug:slug>', confirmarCotizacion, name='confirmar-cotizacion'),
    path('cotizacion/rechazar/<slug:slug>', rechazarCotizacion, name='rechazar-cotizacion'),
    path('cotizacion/editar/<slug:slug>', CotizacionUpdate.as_view(), name='editar-cotizacion'),
    path('cotizacion/detalle/<slug:slug>', CotizacionDetalle.as_view(), name='detalle-cotizacion'),
    path('cotizacion/cancelar/<slug:slug>', CotizacionCancel.as_view(), name='cancelar-cotizacion'),
    path('pagar/seguro/<slug:slug>', SeleccionarSeguro.as_view(), name='seleccionar-seguro'),
    path('pagar/checkout/<slug:slug>', checkout.as_view(), name='checkout'),
    path('pagar/<slug:slug>', PagarCotizacion, name='pagar-cotizacion'),
    path('viajes/', ViajesListView.as_view(), name='viajes'),
    path('viajes/cancelar/<slug:slug>', ViajeCancel.as_view(), name='cancelar-viaje'),
    path('viaje/detalle/<slug:slug>', ViajesDetalle.as_view(), name='detalle-viaje'),
    path('viaje/nipsviaje/<slug:slug>', dataViajeSeguridad, name='data-seguridad-viaje'),
    path('viaje/registrarsalida/<slug:slug>', registrarSalida, name='registrar-salida-viaje'),
    path('viaje/registrarllegada/<slug:slug>', registrarLlegada, name='registrar-llegada-viaje'),
    path('viaje/finalizar/<slug:slug>', finalizarViaje, name='finzalizar-viaje'),
    path('viaje/evidencias/<slug:slug>', ViajesEvidencias.as_view(), name='evidencias-viaje'),
    path('destino/agregarevidencia/<int:pk>', DestinoAregarEvidencia.as_view(), name='agregar-evidencia-destino'),
    #path('destino/descargarevidencia/<int:destino>', download_image, name='descargar-evidencia'),
    path('viaje/agregarfacturas/<slug:slug>', ViajeAregarFacturas.as_view(), name='agregar-facturas-viaje'),
]